spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/wallet}
    username: ${DB_USER:wallet}
    password: ${DB_PASSWORD:wallet}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:50}
      minimum-idle: ${DB_POOL_MIN_IDLE:10}
      connection-timeout: ${DB_CONN_TIMEOUT_MS:2000}
      validation-timeout: ${DB_VALID_TIMEOUT_MS:1000}
      idle-timeout: ${DB_IDLE_TIMEOUT_MS:600000}
      max-lifetime: ${DB_MAX_LIFETIME_MS:1800000}

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

logging:
  level:
    root: ${LOG_LEVEL:INFO}
