server:
  port: ${APP_PORT:8080}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/wallet}
    username: ${DB_USER:wallet}
    password: ${DB_PASSWORD:wallet}

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

logging:
  level:
    root: ${LOG_LEVEL:INFO}